CREATE OR ALTER TABLE GIT_DEV.RAW.TEST_TABLE (
  ID STRING,
  TEXT_FIELD STRING,
  TEXT_FIELD_2 STRING
);

CREATE OR ALTER TABLE GIT_DEV.RAW.TICKER (
  VARIANT_FIELD VARIANT
);

CREATE OR ALTER TABLE GIT_DEV.RAW.OHLC (
  VARIANT_FIELD VARIANT
);