--!jinja
CREATE OR ALTER TABLE {{environment}}.RAW.TEST_TABLE (
  ID STRING,
  TEXT_FIELD STRING,
  TEXT_FIELD_2 STRING
);

CREATE OR ALTER TABLE {{environment}}.RAW.TICKER (
  VARIANT_FIELD VARIANT
);

CREATE OR ALTER TABLE {{environment}}.RAW.OHLC (
  VARIANT_FIELD VARIANT
);